In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import time
from datetime import datetime


import sys
import os

In [36]:
# MAGIA (não mexer mt pfv)
def show_args(func):
    def wrapper(*args, **kwargs):
        arg_list = []

        # Prepare argument list
        for name, value in zip(func.__code__.co_varnames, args):
            if isinstance(value, pd.DataFrame):
                arg_list.append(f"{name}: DataFrame ({value.shape})")
            else:
                arg_list.append(f"{name}: {value}")
        for k, v in kwargs.items():
            if isinstance(v, pd.DataFrame):
                arg_list.append(f"{k}: DataFrame ({v.shape})")
            else:
                arg_list.append(f"{k}: {v}")

        print(f"Executando <{func.__name__}>\n({'\\n'.join(arg_list)})")

        # Measure execution time
        start = time.perf_counter()
        result = func(*args, **kwargs)
        end = time.perf_counter()

        print(f"Tempo de execução: {end - start:.6f} segundos\n")
        return result
    return wrapper

In [37]:
from pathlib import Path
import pandas as pd

@show_args
def csvs_to_parquet(input_folder, output_folder):
    input_path = Path(input_folder)
    output_path = Path(output_folder)
    output_path.mkdir(parents=True, exist_ok=True)

    for csv_file in input_path.glob("*.csv"):
        try:
            df = pd.read_csv(csv_file, encoding="utf-8")
        except UnicodeDecodeError:
            df = pd.read_csv(csv_file, encoding="latin1")

        parquet_file = output_path / csv_file.with_suffix(".parquet").name
        df.to_parquet(parquet_file, index=False)

In [38]:
#csvs_to_parquet("../data/data/refined/csvs", "../data/data/refined/parquets")

In [39]:
articles_subject_areas_raw = pd.read_parquet('../data/data/refined/parquets/article_subject_areas.parquet').rename(columns={
    'eid': 'art_id',
    'subject area code': 'sub_id'
})[['art_id', 'sub_id']] # A

articles_raw = pd.read_parquet('../data/data/refined/parquets/article.parquet').rename(columns={
    'eid': 'art_id',
    'subtype description': 'art_subtype',
    'title': 'art_title',
    'published date': 'art_published_date',
    'cited by count': 'art_citations',
    'source id' : 'art_source',
    'aggregation type' : 'art_source_type'
})[['art_id', 'art_subtype', 'art_title', 'art_published_date', 'art_citations', 'art_source', 'art_source_type']] # B

articles_authors_raw = pd.read_parquet('../data/data/refined/parquets/articles_author.parquet').rename(columns={
    'eid': 'art_id',
    'auid': 'aut_id',
    'creator': 'main_writer'
})[['art_id', 'aut_id', 'main_writer']] # B  C

articles_institutions_raw = pd.read_parquet('../data/data/refined/parquets/articles_institution.parquet').rename(columns={
    'eid': 'art_id',
    'afid': 'ins_id',
    'creator': 'main_writer',
    'country': 'ins_country'
})[['art_id', 'ins_id', 'main_writer', 'ins_country']]

authors_raw = pd.read_parquet('../data/data/refined/parquets/author.parquet').rename(columns={
    'auid': 'aut_id',
    'given name': 'aut_name',
    'surname': 'aut_surname',
    'indexed name': 'aut_indexed_name'
})[['aut_id', 'aut_name', 'aut_surname', 'aut_indexed_name']] # C

scores_raw = pd.read_parquet('../data/data/refined/parquets/CiteScore_2024_annual_values.parquet').rename(columns={
    'Scopus Source ID' : 'art_source',
    'Title' : 'src_title',
    'Citation Count' : 'src_citation_count',
    'CiteScore' : 'src_citescore',
    'Percentile' : 'src_percentile',
    'RANK' : 'src_rank',
    'Rank Out Of' : 'src_rank_count',
    'Quartile' : 'src_quartile'
})[['art_source', 'src_title', 'src_citation_count', 'src_citescore', 'src_percentile', 'src_rank', 'src_rank_count', 'src_quartile']]


departments_raw = pd.read_parquet('../data/data/refined/parquets/departments.parquet').rename(columns={
    'afid' : 'ins_id',
    'dptid': 'dpt_id',
    'organization': 'dpt_name',
    'country' : 'dpt_country',
    'city' : 'dpt_city'
})[['ins_id', 'dpt_id', 'dpt_name', 'dpt_country', 'dpt_city']]


institutions_raw = pd.read_parquet('../data/data/refined/parquets/institutions.parquet').rename(columns={
    'Código Mantenedora': 'ins_maint_code',
    'Razão Social': 'ins_legal_name',
    'Município' : 'ins_city',
    'UF' : 'ins_state',
    'Tipo de Credenciamento' : 'ins_modalidade',
    'Categoria' : 'ins_category',
    'CI' : 'ins_ci',
    'Ano CI' : 'ins_ci_year',
    'CI-EaD' : 'ins_ci_ead',
    'Ano CI-EaD' : 'ins_ci_ead_year',
    'IGC' : 'ins_igc',
    'Ano IGC' : 'ins_igc_year',
    'Situação da IES' : 'ins_status',
    'eid' : 'art_id',
    'afid' : 'ins_id',
    'name' : 'ins_name'
})[['ins_maint_code', 'ins_legal_name', 'ins_city', 'ins_state', 'ins_modalidade',
   'ins_category', 'ins_ci', 'ins_ci_year', 'ins_ci_ead', 'ins_ci_ead_year',
   'ins_igc', 'ins_igc_year', 'ins_status', 'art_id', 'ins_id', 'ins_name']]

subject_areas_raw = pd.read_parquet('../data/data/refined/parquets/subject_area.parquet')
subject_areas_raw.columns = ['sub_id', 'sub_name', 'sub_macro'] # A





#authors_institutions_raw = pd.read_parquet('../data/data/refined/parquets/authors_institution.parquet').rename(columns={
#    'affiliation id': 'aff_id',
#    'auid': 'author_id',
#    'dptid': 'dpt_id'
#})

In [40]:
articles_institutions_raw.head()

               art_id    ins_id  main_writer    ins_country
0  2-s2.0-85014271417  60029570         True         Brazil
1  2-s2.0-85014271417  60031257        False         Brazil
2  2-s2.0-85014271417  60020457        False         Brazil
3  2-s2.0-84951935294  60008088         True         Brazil
4  2-s2.0-84951935294  60021235        False  United States

In [42]:

authors_info = (
    articles_authors_raw
    .merge(authors_raw, on='aut_id', how='inner')
    .groupby('art_id', as_index=False)
    .agg({
        'aut_name': list,
        'aut_surname': list,
        'aut_indexed_name': list,
        'main_writer': list
    })
)


subjects_info = (
    articles_subject_areas_raw
    .merge(subject_areas_raw, on='sub_id', how='inner')
    .groupby('art_id', as_index=False)
    .agg({
        'sub_name': list,
        'sub_macro': list
    })
)


institutions_info = (
    articles_institutions_raw[['art_id', 'ins_id', 'ins_country']]  
    .merge(institutions_raw[['ins_id', 'ins_name']], on='ins_id', how='left')
    .groupby('art_id', as_index=False)
    .agg({
        'ins_id': list,
        'ins_name': list,
        'ins_country': list
    })
)

#departments_info = (
#    departments_raw[['ins_id', 'dpt_name', 'dpt_city', 'dpt_country']]
#    .groupby('ins_id', as_index=False)
#    .agg({
#        'dpt_name': list,
#        'dpt_city': list,
#        'dpt_country': list
#    })
#)



articles_institutions_raw['ins_id'] = articles_institutions_raw['ins_id'].astype(str)
institutions_raw['ins_id'] = institutions_raw['ins_id'].astype(str)
#departments_raw['ins_id'] = departments_raw['ins_id'].astype(str)


main = (
    articles_raw
    .merge(subjects_info, on='art_id', how='inner')
    .merge(authors_info, on='art_id', how='inner')
    .merge(institutions_info, on='art_id', how='inner')
    .merge(scores_raw, on='art_source', how='inner')
)


#main = main.merge(departments_info, on='ins_id', how='left')

In [ ]:
main.head()

,art_id,art_subtype,art_title,art_published_date,art_citations,art_source,art_source_type,sub_name,sub_macro,aut_name,...,ins_id,ins_name,ins_country,src_title,src_citation_count,src_citescore,src_percentile,src_rank,src_rank_count,src_quartile
0,2-s2.0-85014271417,Article,Effect of Bioglass 45S5 air-abrasion on dentin...,2015-12-22,4.0,2.110079e+10,Journal,"[Dentistry (miscellaneous), Surfaces, Coatings...","[DENT, MATE, MATE, MATE]","[Mário Alexandre Coelho, Gabriel, Rafael Pino,...",...,"[60029570, 60031257, 60020457]","[Universidade Estadual de Campinas, Universida...","[Brazil, Brazil, Brazil]",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2-s2.0-84951935294,Article,Body adiposity index performance in estimating...,2015-12-30,18.0,1.265300e+04,Journal,"[Medicine (miscellaneous), Nutrition and Diete...","[MEDI, NURS]","[Giliane, Lilian Mika, Priscila Campos, Raquel...",...,"[60008088, 60021235]","[Universidade de São Paulo, nan]","[Brazil, United States]",Nutrition Journal,2502.0,6.7,83.0,71.0,433.0,1.0
2,2-s2.0-84951935294,Article,Body adiposity index performance in estimating...,2015-12-30,18.0,1.265300e+04,Journal,"[Medicine (miscellaneous), Nutrition and Diete...","[MEDI, NURS]","[Giliane, Lilian Mika, Priscila Campos, Raquel...",...,"[60008088, 60021235]","[Universidade de São Paulo, nan]","[Brazil, United States]",Nutrition Journal,2502.0,6.7,74.0,37.0,144.0,2.0
3,2-s2.0-84962773076,Article,Correlation of oxytocin (OTR) and estrogen rec...,2015-12-31,1.0,6.500153e+09,Journal,"[Animal Science and Zoology, General Veterinary]","[AGRI, VETE]","[Gisele Almeida, Marcilio, Cristina Fátima, Li...",...,"[60008088, 110455370]","[Universidade de São Paulo, nan]","[Brazil, Brazil]",American Journal of Animal and Veterinary Scie...,391.0,2.2,61.0,77.0,200.0,2.0
4,2-s2.0-84962773076,Article,Correlation of oxytocin (OTR) and estrogen rec...,2015-12-31,1.0,6.500153e+09,Journal,"[Animal Science and Zoology, General Veterinary]","[AGRI, VETE]","[Gisele Almeida, Marcilio, Cristina Fátima, Li...",...,"[60008088, 110455370]","[Universidade de São Paulo, nan]","[Brazil, Brazil]",American Journal of Animal and Veterinary Scie...,391.0,2.2,55.0,226.0,509.0,2.0

In [43]:
teste = main.head(1000)
teste.to_csv('teste.csv')

In [44]:
main.columns

Index(['art_id', 'art_subtype', 'art_title', 'art_published_date',
       'art_citations', 'art_source', 'art_source_type', 'sub_name',
       'sub_macro', 'aut_name', 'aut_surname', 'aut_indexed_name',
       'main_writer', 'ins_id', 'ins_name', 'ins_country', 'src_title',
       'src_citation_count', 'src_citescore', 'src_percentile', 'src_rank',
       'src_rank_count', 'src_quartile'],
      dtype='object')

In [45]:
main['ins_name'].head()

0               [Universidade de São Paulo, nan]
1               [Universidade de São Paulo, nan]
2               [Universidade de São Paulo, nan]
3               [Universidade de São Paulo, nan]
4    [nan, nan, Universidade Federal Fluminense]
Name: ins_name, dtype: object